### ISSUE TITLE
Avoid url-loader

### ISSUE THREAD

**Issue by 3846masa** [ukeyshima/ukeyshima.github.io#2]
Your website is very slow.
I think it causes because you converted images to base64 via url-loader.
Please consider to use [file-loader].

[file-loader]: https://github.com/webpack-contrib/file-loader

**Comment by ukeyshima** [comment]
Thank you, 3846masa!
I am now fixing that problem...
I am sorry to inconvenience you.

**Comment by 3846masa** [comment]
Never mind. I hope this helps.

**Comment by ukeyshima** [comment]
いやぁきついっす

**Comment by ukeyshima** [comment]
I did it!
d87d37e5b38f1f2900026994016b1c6b88d5c750

**Comment by 3846masa** [comment]
Why not remove `url-loader`?
https://github.com/ukeyshima/ukeyshima.github.io/blob/d87d37e5b38f1f2900026994016b1c6b88d5c750/webpack.config.js#L26-L29

**Comment by ukeyshima** [comment]
I did it! 
981999bd9f847c15b162ba93ab22ffd8171b5208

**Comment by ukeyshima** [comment]
Close this issue!
